security:
  basic:
    enabled: false

management:
  security:
    enabled: false

loggin:
  level:
    io:
      pivotal: DEBUG

spring: # <---NEW SECTION
  cloud:
    services:
      registrationMethod: direct
