security:
  basic:
    enabled: false # turn off securing our application endpoints

management:
  security:
    enabled: false # turn off securing the actuator enpoints

logging: # <----New sections below
  level:
    io:
      pivotal: DEBUG

greeting: # fortune?
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
